# Setup
title:               Minwoo
tagline:             "writings"
description:         'Awe - some'
url:                 https://tommybebe.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Minwoo
  url:               https://tommybebe.github.io
  email:             hansupanda@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# Custom vars
version:             1.1.0
google_tagmanager_id: GTM-KTQDN3B
